services:
  rag-backend:
    container_name: rag-backend
    build: .
    restart: always
    volumes:
      - ./data:/app/data
      - ./model:/app/model
    env_file:
      - ./Env.env
    ports:
      - "8347:8347"
    networks:
      - rag-network

  rag-frontend:
    image: nginx:1.20.2
    container_name: rag-frontend
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html
    networks:
      - rag-network

networks:
  rag-network:
    external: true



